version: '3'

services:
  pgsql:
    build:
      context: ./pgsql
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  mariadb:
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"

  apache2:
    build:
      context: ./apache2
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${APACHE_SITES_PATH}:/usr/local/apache2/conf/sites
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"

  nginx:
    build:
      context: ./nginx
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"

  php71:
    build:
      context: ./php71
      args:
        - INSTALL_BZ2=${PHP71_INSTALL_BZ2}
        - INSTALL_SOAP=${PHP71_INSTALL_SOAP}
        - INSTALL_XSL=${PHP71_INSTALL_XSL}
        - INSTALL_BCMATH=${PHP71_INSTALL_BCMATH}
        - INSTALL_PHPREDIS=${PHP71_INSTALL_PHPREDIS}
        - INSTALL_OPCACHE=${PHP71_INSTALL_OPCACHE}
        - INSTALL_EXIF=${PHP71_INSTALL_EXIF}
        - INSTALL_MYSQLI=${PHP71_INSTALL_MYSQLI}
        - INSTALL_PGSQL=${PHP71_INSTALL_PGSQL}
        - INSTALL_INTL=${PHP71_INSTALL_INTL}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP71_INSTALL_IMAGE_OPTIMIZERS}
        - INSTALL_IMAGEMAGICK=${PHP71_INSTALL_IMAGEMAGICK}
        - INSTALL_GETTEXT=${PHP71_INSTALL_GETTEXT}
        - INSTALL_ADDITIONAL_LOCALES=${INSTALL_ADDITIONAL_LOCALES}
        - INSTALL_PCNTL=${PHP71_INSTALL_PCNTL}
        - INSTALL_COMPOSER=${PHP71_INSTALL_COMPOSER}
        - ADDITIONAL_LOCALES=${ADDITIONAL_LOCALES}
        - PUID=${PUID}
        - PGID=${PGID}
        - LOCALE=${DEFAULT_LOCALE}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./php71/php.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}

  php72:
    build:
      context: ./php72
      args:
        - INSTALL_BZ2=${PHP72_INSTALL_BZ2}
        - INSTALL_SOAP=${PHP72_INSTALL_SOAP}
        - INSTALL_XSL=${PHP72_INSTALL_XSL}
        - INSTALL_BCMATH=${PHP72_INSTALL_BCMATH}
        - INSTALL_PHPREDIS=${PHP72_INSTALL_PHPREDIS}
        - INSTALL_OPCACHE=${PHP72_INSTALL_OPCACHE}
        - INSTALL_EXIF=${PHP72_INSTALL_EXIF}
        - INSTALL_MYSQLI=${PHP72_INSTALL_MYSQLI}
        - INSTALL_PGSQL=${PHP72_INSTALL_PGSQL}
        - INSTALL_INTL=${PHP72_INSTALL_INTL}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP72_INSTALL_IMAGE_OPTIMIZERS}
        - INSTALL_IMAGEMAGICK=${PHP72_INSTALL_IMAGEMAGICK}
        - INSTALL_GETTEXT=${PHP72_INSTALL_GETTEXT}
        - INSTALL_ADDITIONAL_LOCALES=${INSTALL_ADDITIONAL_LOCALES}
        - INSTALL_PCNTL=${PHP72_INSTALL_PCNTL}
        - INSTALL_COMPOSER=${PHP72_INSTALL_COMPOSER}
        - ADDITIONAL_LOCALES=${ADDITIONAL_LOCALES}
        - PUID=${PUID}
        - PGID=${PGID}
        - LOCALE=${DEFAULT_LOCALE}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./php72/php.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
