version: '3'

services:
  pgsql:
    build:
      context: ./pgsql
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  mariadb:
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"

  apache2:
    build:
      context: ./apache2
      args:
        - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${APACHE_SITES_PATH}:/usr/local/apache2/conf/sites
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"


  # pgsql:
  #   image: postgres:11-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=secret
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./pgsql/data:/var/lib/postgresql/data/pgdata

  # mariadb:
  #   image: mariadb
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=secret
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mariadb/data:/var/lib/mysql

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis/data:/data

  # apache:
  #   build:
  #     context: ./apache
  #   ports:
  #     - "80:80"
  #   working_dir: /code
  #   volumes:
  #     - ${WEB_ROOT}:/code

  # nginx:
  #   build:
  #     context: ./nginx
  #   ports:
  #     - "80:80"
  #   working_dir: /code
  #   volumes:
  #     - ${WEB_ROOT}:/code

  # php71:
  #   build:
  #     context: ./php71
  #   working_dir: /code
  #   volumes:
  #     - ${WEB_ROOT}:/code

  # php72:
  #   build:
  #     context: ./php72
  #   working_dir: /code
  #   volumes:
  #     - ${WEB_ROOT}:/code
