version: '3'

services:
  pgsql:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data/pgdata

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  apache:
    build:
      context: ./apache
    ports:
      - "80:80"
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  php71:
    build:
      context: ./php71
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code

  php72:
    build:
      context: ./php72
    working_dir: /code
    volumes:
      - ${WEB_ROOT}:/code
